version: "3.8"

services:
  client:
    build:
      context: ./fishingcom-client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./fishingcom-client:/client
    depends_on:
      - server
  server:
    build:
      context: ./fishingcom-server
      dockerfile: Dockerfile.dev
    ports:
      - "8585:8585"
    volumes:
      - ./fishingcom-server:/server
